config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :records do
    resources :tracks
  end
  root 'records#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/record.rb
class Record < ApplicationRecord
  has_many :tracks, dependent: :destroy
  validates :artist, presence: true
  validates :album, presence: true
  validates :year_printed, presence: true, numericality: {greater_than_or_equal_to: 1900, less_than_or_equal_to: Time.current.year}
  validates :year_released, presence: true, numericality: {greater_than_or_equal_to: 1900, less_than_or_equal_to: Time.current.year}
  validates :condition, presence: true, numericality: {greater_than_or_equal_to: 1, less_than_or_equal_to: 10}
end

app/models/track.rb
class Track < ApplicationRecord
  belongs_to :record
end

app/models/vinyl.rb
class Vinyl < ApplicationRecord
  has_many :tracks
  validates :artist, presence: true
  validates :album, presence: true
  validates :year_printed, presence: true, numericality: {greater_than_or_equal_to: 1900, less_than_or_equal_to: Time.current.year}
  validates :year_released, presence: true, numericality: {greater_than_or_equal_to: 1900, less_than_or_equal_to: Time.current.year}
  validates :condition, presence: true, numericality: {greater_than_or_equal_to: 1, less_than_or_equal_to: 10}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  http_basic_authenticate_with name: "user", password: "pass"
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController

  http_basic_authenticate_with name: "user", password: "pass"

  def index
    @records = Record.all
  end

  def show
    @record = Record.find(params[:id])
  end

  def new
    @record = Record.new
  end

  def edit
    @record = Record.find(params[:id])
  end

  def update
    @record = Record.find(params[:id])
    if @record.update(record_params)
      redirect_to @record
    else
      render 'edit'
    end
  end

  def create
    @record = Record.new(record_params)
    if @record.save
      redirect_to @record
    else
      render 'new'
    end
  end

  def destroy
    @record = Record.find(params[:id])
    @record.destroy
    redirect_to records_path
  end

  private

  def record_params
    params.require(:record).permit(:artist, :album, :year_released, :year_printed, :condition)
  end

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  http_basic_authenticate_with name: "user", password: "pass"

  def create
    @record = Record.find(params[:record_id])
    @track = @record.tracks.create(track_params)
    redirect_to record_path(@record)
  end

  def destroy
    @record = Record.find(params[:record_id])
    @track = @record.tracks.find(params[:id])
    @track.destroy
    redirect_to record_path(@record)
  end

  private

  def track_params
    params.require(:track).permit(:title)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyVinylRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/records/_form.html.erb
<%= form_with model: @record, local: true do |form| %>
  <div class="form-group">
    <%= form.label :artist %>
    <%= form.text_field :artist, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :album %>
    <%= form.text_field :album, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :year_released %>
    <%= form.number_field :year_released, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :year_printed %>
    <%= form.number_field :year_printed, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :condition %>
    <%= form.select(:condition, ["", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10"], {}, {:class => "form-control"}) %>
  </div>
  <%= form.submit :class => "btn btn-primary" %>
<% end %>

<% if @record.errors.any? %>
  <div id="error_explanation">
    <strong>
      <%= pluralize(@record.errors.count, "error") %> prohibited this record from being saved:
    </strong>
    <ul>
      <% @record.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/records/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-8 col-md-5">
      <h1>Edit Record</h1>
      <p>
        <%= link_to 'Cancel', records_path %> |
        <%= link_to 'View', record_path %>
      </p>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/records/index.html.erb
<div class="jumbotron">
  <h1 class="display-3">Record Collection</h1>
  <p class="lead">
    This is a simple application where you can manage your record collection.
  </p>
  <hr class="my-4">
  <%= link_to 'Add Record', new_record_path, :class => "btn btn-primary btn-lg" %>
</div>
<table class="table">
  <tr>
    <th>Artist</th>
    <th>Album</th>
    <th>Year Released</th>
    <th>Year Printed</th>
    <th>Condition</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <% @records.each do |record| %>
    <tr>
      <td><%= record.artist %></td>
      <td><%= record.album %></td>
      <td><%= record.year_released %></td>
      <td><%= record.year_printed %></td>
      <td><%= record.condition %></td>
      <td><%= link_to 'View', record_path(record) %></td>
      <td><%= link_to 'Edit', edit_record_path(record) %></td>
      <td><%= link_to 'Delete', record_path(record),
                      method: :delete,
                      data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
</table>

app/views/records/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-8 col-md-5">
      <h1>New Record</h1>
      <p>
        <%= link_to 'Cancel', records_path %>
      </p>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/records/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-8 col-md-5">
      <h1><%= @record.album %></h1>
      <p>
        <%= link_to 'Edit', edit_record_path(@record) %> |
        <%= link_to 'Records', records_path %>
      </p>
      <div class="row pb-2">
        <div class="col-4">
          <strong>Artist:</strong>
        </div>
        <div class="col-8 text-right">
          <%= @record.artist %>
        </div>
      </div>
      <div class="row pb-2">
        <div class="col-4">
          <strong>Album:</strong>
        </div>
        <div class="col-8 text-right">
          <%= @record.album %>
        </div>
      </div>
      <div class="row pb-2">
        <div class="col-4">
          <strong>Year Released:</strong>
        </div>
        <div class="col-8 text-right">
          <%= @record.year_released %>
        </div>
      </div>
      <div class="row pb-2">
        <div class="col-4">
          <strong>Year Printed:</strong>
        </div>
        <div class="col-8 text-right">
          <%= @record.year_printed %>
        </div>
      </div>
      <div class="row pb-2">
        <div class="col-4">
          <strong>Condition:</strong>
        </div>
        <div class="col-8 text-right">
          <%= @record.condition %>
        </div>
      </div>

      <hr class="my-4">

      <p>
        <strong>Tracks:</strong>
      </p>

      <%= render @record.tracks %>

      <p>
        <strong>Add a track:</strong>
      </p>

      <%= render 'tracks/form' %>
    </div>
  </div>
</div>

app/views/tracks/_form.html.erb
<%= form_with(model: [@record, @record.tracks.build], local: true) do |form| %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, :class => "form-control" %>
  </div>
  <%= form.submit :class => "btn btn-primary" %>
<% end %>

app/views/tracks/_track.html.erb
<div class="row pb-2">
  <li class="col-6">
    <%= track.title %>
  </li>
  <div class="col-6 text-right">
    <%= link_to 'Destroy Track', [track.record, track],
                method: :delete,
                data: {confirm: 'Are you sure?'} %>
  </div>
</div>

app/views/vinyl/_form.html.erb
<%= form_with model: @vinyl, local: true do |form| %>
  <p>
    <%= form.label :artist %><br>
    <%= form.text_field :artist %>
  </p>

  <p>
    <%= form.label :album %><br>
    <%= form.text_field :album %>
  </p>

  <p>
    <%= form.label :year_released %><br>
    <%= form.number_field :year_released %>
  </p>

  <p>
    <%= form.label :year_printed %><br>
    <%= form.number_field :year_printed %>
  </p>

  <p>
    <%= form.label :condition %><br>
    <%= form.select :condition, ["", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10"] %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

<% if @vinyl.errors.any? %>
  <div id="error_explanation">
    <strong>
      <%= pluralize(@vinyl.errors.count, "error") %> prohibited
      this vinyl from being saved:
    </strong>
    <ul>
      <% @vinyl.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/vinyl/new.html.erb
<h1>New Vinyl</h1>

<p>
  <%= link_to 'Cancel', vinyl_index_path %>
</p>

<%= form_with scope: :vinyl, url: {:controller => "vinyl", :action => "create"}, local: true do |form| %>
  <p>
    <%= form.label :artist %><br>
    <%= form.text_field :artist %>
  </p>

  <p>
    <%= form.label :album %><br>
    <%= form.text_field :album %>
  </p>

  <p>
    <%= form.label :year_released %><br>
    <%= form.number_field :year_released %>
  </p>

  <p>
    <%= form.label :year_printed %><br>
    <%= form.number_field :year_printed %>
  </p>

  <p>
    <%= form.label :condition %><br>
    <%= form.select :condition, ["", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10"] %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

<% if @vinyl.errors.any? %>
  <div id="error_explanation">
    <strong>
      <%= pluralize(@vinyl.errors.count, "error") %> prohibited
      this vinyl from being saved:
    </strong>
    <ul>
      <% @vinyl.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>